# standard jekyll configuration

permalink: /:year/:title/
highlighter:  pygments
exclude: ['readme.md', 'Procfile', 'config.rb', '.gitignore', '.sass-cache', 'Gemfile', 'Gemfile.lock', 'Rakefile', '_linked-data']
show_drafts: false

title: Com<i>·</i>post
author: Purdom Lindblad
domain: http://purdom.org
