# standard jekyll configuration

permalink: /:year/:title/
highlighter:  pygments
exclude: ['readme.md', 'Procfile', 'config.rb', '.gitignore', '.sass-cache', 'Gemfile', 'Gemfile.lock']
show_drafts: false

title: Z
author: Purdom Lindblad
domain: http://purdom.org
